# Generated by Django 5.2.7 on 2025-10-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('avatar', models.ImageField(help_text='建议尺寸为500*755', upload_to='team', verbose_name='头像')),
                ('title', models.CharField(max_length=20, verbose_name='职务')),
                ('rank', models.IntegerField()),
            ],
            options={
                'verbose_name': '团队管理',
                'verbose_name_plural': '团队管理',
                'db_table': 'team',
            },
        ),
    ]
