# Generated by Django 5.2.7 on 2025-10-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='推荐尺寸：1920*1280', upload_to='slide', verbose_name='幻灯片名字')),
                ('title', models.CharField(help_text='一级标题', max_length=100, verbose_name='标题')),
                ('content', models.CharField(help_text='二级标题', max_length=1000, verbose_name='内容')),
            ],
            options={
                'verbose_name': '幻灯片管理',
            },
        ),
    ]
