# Generated by Django 5.2.7 on 2025-10-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slide',
            table='slide',
        ),
    ]
