# Generated by Django 5.2.7 on 2025-10-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0002_alter_slide_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': '幻灯片管理', 'verbose_name_plural': '幻灯片管理'},
        ),
    ]
